### ISSUE TITLE
Firefox 57.0 + Greasemonkey 4.0 + Facebook last post scroller

### ISSUE THREAD

**Issue by ChuckeryTowers** [soufianesakhi/facebook-last-post-scroller#1]
Since the recent upgrade to Firefox 57.0, the scroller is no longer shown.  Is there a method to bring it back please?

**Comment by soufianesakhi** [comment]
Hello,

Greasemonkey doesn't work well with Firefox 57.
Try Tampermonkey for firefox https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/.

Thanks

**Comment by ChuckeryTowers** [comment]
Thank you for the amazingly fast response.  I am now trying Tampermonkey (version 4.5.5590) - sometimes the scroller buttons are displayed at the top of the Facebook page, but most of the time it seems that they are not.  I have re-opened the Facebook tab, and restarted Firefox.  Reloading the tab seems to bring the buttons back sometimes, clicking "Scroll to last post" makes them disappear again.  The "Set as last post" icons are displayed, but may not be working correctly - several hours' worth of posts have appeared when the fourth post was set as last.  I am sorry for being a bore.

**Comment by soufianesakhi** [comment]
The script only works when the homepage is set to view most recent stories instead of top stories. Can you check if this is the case ?

**Comment by ChuckeryTowers** [comment]
It was.  Scrolling was continuing since my previous post.

**Comment by ChuckeryTowers** [comment]
It was.  Scrolling was continuing since my previous comment here until I closed down Firefox some minutes later.  Since then I have re-opened Firefox, re-opened Facebook, checked that "Most recent" was selected, and clicked "Scroll to last post".  That worked as expected.  Immediately afterwards, going back to the top of the page showed that the "scroller" buttons were gone.  Refreshing the window brought back the buttons.

I wonder: are the "Scroller" buttons meant to be hidden unless a new post has arrived? I do not recall that being the behaviour with Greasemonkey on Firefox 56.  Also, I wonder if there is a maximum limit to the number of posts through which "Scroller" will search.

**Comment by soufianesakhi** [comment]
Yes they are supposed to disappear once you click on them. A page refresh is necessary to make them appear again.
There are no maximum limits.

**Comment by ChuckeryTowers** [comment]
I think that the behaviour is different compared with that under Greasemonkey.  The lack of a maximum never seemed to be a problem previously, but now it seems that Facebook can scroll through old posts for many minutes, a long way past the one that I had marked as read.  I wonder what is causing this.

**Comment by soufianesakhi** [comment]
Sorry I couldn't reproduce (Firefox 57 + Tampermonkey). Did the last post get deleted by any chance ?

**Comment by ChuckeryTowers** [comment]
I am fairly sure that the last post had not been deleted.  Clearly reproduction of circumstances is difficult - is there anything that I can do to help to debug this?

**Comment by soufianesakhi** [comment]
Right now there are logs when a last post is saved along with the timestamp of the post. I will try to add in the future more debugging capabilities.

**Comment by ChuckeryTowers** [comment]
I think that we have now made as much progress as we can.  I have not had any fresh problems, and have grown accustomed to using the scroller as it is.  Perhaps your future efforts might also include adding a configuration option to restrict scrolling to something like 50 or 100 or 200 items, to prevent long sessions of scrolling.  For now, I am happy to close this problem report.  Thank you for the software, and for what you have done to support me.

**Comment by soufianesakhi** [comment]
In the latest version, a toolbar will be displayed to track the progress and to stop the loading & scrolling if it takes too long
